yarnPath: .yarn/releases/yarn-3.6.1.cjs
nodeLinker: pnp

npmScopes:
  "npm-publish-test-core":
    npmAlwaysAuth: true
    npmAuthToken: "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"
    npmRegistryServer: "https://npm.pkg.github.com"
